version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directories:
      - "/"
      - ".github/"
    schedule:
      interval: "weekly"
